#pragma once
#define INF 999999
#define OPTIMAL_VALUE 1130

//Artificial bee colony
#define ABC_POPULATION 500
#define ABC_SCOUT_BEE_POPULATION 1
#define ABC_N_SCOUT_BEE_INSERTIONS 3
#define ABC_TIME_TO_LIVE 100
#define ABC_ADAPTIVE_LIST_SIZE 100
#define ABC_LOCAL_SEARCH_MAX_MUTATIONS 10
#define ABC_LOCAL_SEARCH_CHANCE 0.2
#define ABC_WINNING_LIST_CHANCE 0.75
#define ABC_TOURNAMENT_SIZE 2
#define ABC_MAX_GENERATIONS 10000


//Ant colony